import React from "react";
import ProductCard from "./ProductCard";
import Link from "next/link";
const products = [
  {
    id: 1,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$1299.00",
    discount: "-12%",
    image: "/MacBook 1.png",
    rating: 4.9,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 2,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$1299.00",
    discount: "-12%",
    image: "/MacBook 2.png",
    rating: 4.9,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 3,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$2490,87",
    discount: "-12%",
    image: "/MacBook 3.png",
    rating: 4.9,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 4,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$2490,87",
    discount: "-12%",
    image: "/MacBook 4.png",
    rating: 4.7,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 5,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$1299.00",
    discount: "-12%",
    image: "/MacBook 5.png",
    rating: 4.9,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 6,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$2490,87",
    discount: "-12%",
    image: "/MacBook 6.png",
    rating: 4.8,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 7,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    newPrice: "$2490,87",
    discount: "-12%",
    image: "/MacBook 7.png",
    rating: 4.6,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 8,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$1299.00",
    discount: "-12%",
    image: "/MacBook 8.png",
    rating: 4.5,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 9,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$1299.00",
    discount: "-12%",
    image: "/MacBook 9.png",
    rating: 4.9,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 10,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$2,556.00",
    newPrice: "$2,165.10",
    discount: "-12%",
    image: "/MacBook 10.png",
    rating: 4.3,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 11,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$1299.00",
    discount: "-12%",
    image: "/MacBook 11.png",
    rating: 4.9,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 12,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    newPrice: "$2490,87",
    discount: "-12%",
    image: "/MacBook 12.png",
    rating: 4.3,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 13,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$2490,87",
    discount: "-12%",
    image: "/MacBook 13.png",
    rating: 4.8,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 14,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    oldPrice: "$1410.87",
    newPrice: "$1299.00",
    discount: "-12%",
    image: "/MacBook 14.png",
    rating: 4.9,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
  {
    id: 15,
    name: "Apple MacBook Air 1'' w/ Touch ID (2023) - Space Grey (Apple M2 Chip / 256GB SSD / 8GB RAM) - French",
    newPrice: "$2,365.00",
    discount: "-12%",
    image: "/MacBook 15.png",
    rating: 4.3,
    brand: "Apple",
    ModelName: "Macbook Pro",
    ScreenSize: "13.3 Inches",
    HardDiskSize: "256 GB",
    CPUModel: "core i5",
    Display: "13.3-inch (diagonal) LED-backlit display with IPS technology",
    Graphics: "Apple 10-core GPU",
    Processor: "Apple M2 chip",
    InTheBox: "67W USB-C Power Adapter, USB-C Charge Cable (2 m)",
    Height: "0.61 inch (1.56 cm)",
    Width: "11.97 inches (30.41 cm)",
  },
];
const ProductList = () => {
  return (
    <div className="flex justify-between flex-wrap gap-6 my-6">
      {products.map((product) => (
        <ProductCard
          key={product.id}
          name={<Link href={`/products/${product.id}`}>{product.name}</Link>}
          oldPrice={product.oldPrice}
          newPrice={product.newPrice}
          discount={product.discount}
          image={product.image}
          rating={product.rating}
        />
      ))}
    </div>
  );
};

export default ProductList;
export { products };
